### ISSUE TITLE
'firebird' isn't an available database backend.

### ISSUE THREAD

**Issue by manuscle** [maxirobaina/django-firebird#100]
Hi,
I'm new with Django.
I've installed django-firebird via pip install as explained in the doc but i get the following error when I run the server:
```
django.core.exceptions.ImproperlyConfigured: 'firebird' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```
django-firebird 1.11
django 2.1 
python 3.6

**Comment by manuscle** [comment]
firebird package missing was the first message I got. Then I've installed it.
I'm using PyCharm on xubuntu 18.04
I'm using virtualenv

![image](https://user-images.githubusercontent.com/596562/47901413-2bfd4980-de80-11e8-986d-48106a27bb11.png)

**Comment by maxirobaina** [comment]
The last stable release of django-firebird is 1.11 which is compatible with django 1.11 LTS. This is the recommended version to use.

The version at master branch is just in develop status and is not stable. Also, it's based in django 2.0.x (not 2.1)

So, I recommend to use django 1.11 LTS with django-firebird 1.11
If you want to use django 2.x, use it just with django 2.0 and try with `master` branch version of django-firebird but without garantee that this works

BTW, the symlink to django/db/backends is not needed.

**Comment by manuscle** [comment]
I've installed Django v2.09 and I don't get any errors.
Thanks for your help
Maybe I could help in the future if I decide to use Django for the main project

**Comment by progressify** [comment]
Tested with Django 2.0.13 and all still work (1.11 version downloaded from pip)
