### ISSUE TITLE
utils.typecast_decimal removed?

### ISSUE THREAD

**Issue by e-belair** [maxirobaina/django-firebird#102]
Hi,
I'm using the master branch of django-firebird
Django 2.0.9
In my model I have this field:
`x_etab = models.DecimalField(max_digits=18, decimal_places=10, blank=True, null=True)`
Then I get thid error when I query models:
```
  File "/home/manu/env01/fbtest/venv/lib/python3.6/site-packages/firebird/operations.py", line 249, in convert_decimalfield_value
    value = utils.typecast_decimal(val)
AttributeError: module 'django.db.backends.utils' has no attribute 'typecast_decimal'
```
So I confirm that typecast_decimal is missing in django.db.backends.utils :
https://github.com/django/django/commit/f3e350d6318c20d0d5e2f53f278b9dcc326e1d74#diff-1132e403debb86cff5e5dd3366985796

**Comment by manuscle** [comment]
I forked the project then I changed the code like this:
https://github.com/manuscle/django-firebird/blob/2bcdc76652cd98369dfb8ffe1034db429f8eb3e2/firebird/operations.py#L248
