### ISSUE TITLE
large sets of data

### ISSUE THREAD

**Issue by pszpakowicz** [maxirobaina/django-firebird#104]
When running django-admin with django-firebird on large amount of data, it gives following error:

('Error while preparing SQL statement:\n- SQLCODE: -204\n- Dynamic SQL Error\n- SQL error code = -204\n- Implementation limit exceeded\n- block size exceeds implementation restriction', -204, 335544569)

Same error when trying to get any object via shell, i.e:

z = MyModel.object.all()
z[0]
django.db.utils.DatabaseError: ('Error while preparing SQL statement:\n- SQLCODE: -204\n- Dynamic SQL Error\n- SQL error code = -204\n- Implementation limit exceeded\n- block size exceeds implementation restriction', -204, 335544569)

or even when counting:
len(z)

any workaround ?

**Comment by pszpakowicz** [comment]
I figured that it's related not to data but to query, which is too long.

**Comment by maxirobaina** [comment]
Hi @pszpakowicz 
Ir seems nota like a django-firebird issue.
What versión of Django are hoy using? And fdb?

Please checkpoint it out 

http://www.firebirdfaq.org/faq299/

**Comment by pszpakowicz** [comment]
yes it is FB related. query lengts (statement) lenght in this case.
When django does MyModel.objects.all() it creates query with all fields in form table_name.column_name. If statement excess build in there is a problem.

I don't know if it is fixxable on this level or not. If not you can close issue.

THX
