### ISSUE TITLE
Does the lib work on windows?

### ISSUE THREAD

**Issue by marcelodelta** [maxirobaina/django-firebird#121]
Hello, how is everything ?

Does the lib work on windows?

DATABASES = {
    'default': {
        'ENGINE': 'firebird',
        'NAME': 'C:\Users\jornador\djangoFirebird\django_firebird.fdb', # Path to database or db alias
        'USER': 'SYSDBA',           # Your db user
        'PASSWORD': 'root',    # db user password
        'HOST': '127.0.0.1',        # Your host machine
        'PORT': '3050',             # If is empty, use default 3050
        #'OPTIONS' : {'charset':'ISO8859_1'}
    }
}

  File "C:\Users\jornador\djangoFirebird\settings.py", line 85
    'NAME': 'C:\Users\jornador\django_firebird.fdb', # Path to database or db alias
            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by maxirobaina** [comment]
Hi @marcelodelta 
Yes, It should.

Try it replacing slash (\) by backslash (/) in NAME key.

'NAME': 'C:/Users/jornador/djangoFirebird/django_firebird.fdb',

or better, use alias definition.
