### ISSUE TITLE
Django 3.2 and firebird 3 error connection

### ISSUE THREAD

**Issue by mist099** [maxirobaina/django-firebird#123]
Hi,
I tried to connect from django 3.2 to a local firebird database but I failed.
I followed the instructions but i didn't manage to pair django with my db.
Also, I use Windows and I want to ask what is the propper folder declaration in the connection string.

ex. if my fdb file is in D:\DEV\DJANGO\DJ.FDB, what is the correct string to put in Django. I've tried all kind of combinations but none of that works.

installed add ons in python 3.9.7
fdb
django-firebird 1.11

Thank's

**Comment by mariuz** [comment]
you need to try manual install from git (no example for windows , but it should be something similar with windows python packages)

https://github.com/maxirobaina/django-firebird#installation
