### ISSUE TITLE
Error on django3 with BOOL fields

### ISSUE THREAD

**Issue by wolandius** [maxirobaina/django-firebird#132]
Hello developers! I tried migrating my app from django2 version to django3 version and got some errors on BOOL fields from db.

Error is looks like this:	
`Error in formatting: TypeError: convert_booleanfield_value() missing 1 required positional argument: 'context'
`

connection | <django.db.backends.firebird.base.DatabaseWrapper object at 0x7fb3e2ad0eb0>
-- | --
converter | <bound method DatabaseOperations.convert_booleanfield_value of <django.db.backends.firebird.operations.DatabaseOperations object at 0x7fb3e2ad0e20>>
converters | [(1,   ([<bound method DatabaseOperations.convert_booleanfield_value of <django.db.backends.firebird.operations.DatabaseOperations object at 0x7fb3e2ad0e20>>],    Col(core_application, core.Application.is_included))),  (7,   ([<bound method DatabaseOperations.convert_textfield_value of <django.db.backends.firebird.operations.DatabaseOperations object at 0x7fb3e2ad0e20>>],    Col(core_application, core.Application.S_DESC_ENG))),  (8,   ([<bound method DatabaseOperations.convert_textfield_value of <django.db.backends.firebird.operations.DatabaseOperations object at 0x7fb3e2ad0e20>>],    Col(core_application, core.Application.S_DESC_RU))),  (9,   ([<bound method DatabaseOperations.convert_textfield_value of <django.db.backends.firebird.operations.DatabaseOperations object at 0x7fb3e2ad0e20>>],    Col(core_application, core.Application.F_DESC_ENG))),  (10,   ([<bound method DatabaseOperations.convert_textfield_value of <django.db.backends.firebird.operations.DatabaseOperations object at 0x7fb3e2ad0e20>>],    Col(core_application, core.Application.F_DESC_RU)))]
convs | [<bound method DatabaseOperations.convert_booleanfield_value of <django.db.backends.firebird.operations.DatabaseOperations object at 0x7fb3e2ad0e20>>]
expression | Col(core_application, core.Application.is_included)

Any Ideas how to fix it ?:)

**Comment by mariuz** [comment]
django firebird 2.2.x doesn't work with django 3.x
