### ISSUE TITLE
Time for a name change?

### ISSUE THREAD

**Issue by vgiralt** [maxirobaina/django-firebird#140]
The firebird name collides with the module suggested as driver (firebird-driver) for Django>=3.2. All that was needed was installing under a different name (firebirdsql), changing the symbolic link in Django db.backends to point to this new name and, of course, the name in the settings. Plus, and this is the quid, a line in operations.py (19: changing "firebird.compiler" to "firebirdsql.complier"). I can do a pull request if needed.

Then, it worked like charm.

**Comment by maxirobaina** [comment]
Close this for duplicated with  #130
