### ISSUE TITLE
There's some plan to update django-firebird to new django releases(>=1.8)?

### ISSUE THREAD

**Issue by raelmax** [maxirobaina/django-firebird#38]
I've tried to use django-firebird with django 1.7 and 1.8 and it don't work. The support to new django releases are in the project roadmap?

Thanks.

**Comment by mariuz** [comment]
Hello you can test the develop branch for 1.7.x support and send us feedback or pull requests 

http://www.firebirdnews.org/firebird-django-1-7-support-experimental/

**Comment by cfingerh** [comment]
Hi, i did modify a master clone to work with django 1.8.
The changes are the minimal necessary to make it work and not complete: Migration was not tested (and I had to disable check_migrations in the main django code (runserver.py).

The most important changes:
1.- new import paths in almost all files
2.- Modify lookup_cast function to include  internal_type=None (but not used in the function)
3.- rewrite of get_table_list function in instrospection.py

**Comment by maxirobaina** [comment]
Hi @cfingerh 
Great! I'll try to check this out latter.

**Comment by CountZachula** [comment]
Any updates on this?

**Comment by maxirobaina** [comment]
The master branch of this repository contains now an alpha version with django 1.8.x supports
I'll appreciate any feedback.
