### ISSUE TITLE
litlle Problem with install

### ISSUE THREAD

**Issue by calhemp** [maxirobaina/django-firebird#46]
sorry i'm newbie, if I install with 'pip install djano-firebird' it works ok. but I think that doesn't install your latest version.

but if I tried to manual install with
```
git clone git://github.com/maxirobaina/django-firebird.git
cd django-firebird
sudo python setup.py install
```
I get this
```
Traceback (most recent call last):
File "setup.py", line 14, in <module>
version = __import__('firebird').get_version()
AttributeError: 'module' object has no attribute 'get_version'
```

is normal? or I'm doing things wrong.
I tried with a python2.7 or with a mkvirtualenv with python3.4

thanks in advance.

**Comment by mariuz** [comment]
did you activated the ENV ?

works without issues on ubuntu 15.10
https://virtualenv.readthedocs.org/en/latest/userguide.html
pip install virtualenv
virtualenv ENV

source ENV/bin/activate

ENV)mariuz@Lorkstation64:/tmp/django-firebird$ python setup.py install
(ENV)mariuz@Lorkstation64:/tmp/django-firebird$ ls ENV/lib/python2.7/site-packages/django_firebird-1.7a0-py2.7.egg/

**Comment by mariuz** [comment]
@maxirobaina this can be closed

**Comment by maxirobaina** [comment]
Hi @calhemp 

Like @mariuz said you need to activate de virtualenv first.
If you use virtualenv do not install using 'sudo', because otherwise it will installed on system wide and not into your env.

Try again and tell me if you have any problem.

Regards.

**Comment by calhemp** [comment]
sorry guys, I was my fault :(, I don't know, but with a new git clone it solves, reading my first download, and compare it with the old, I touched firebird init py file with my editor.

sorry, I can try to test an example with django and firebird, my first time in python.

thanks and sorry.  good day
