### ISSUE TITLE
pip install django-firebird don't intall correctly 

### ISSUE THREAD

**Issue by ilizaran** [maxirobaina/django-firebird#47]
>pip install django-firebird
There are not firebird folder in ..../django/db/backends
Thanks
Regards

**Comment by mariuz** [comment]
what version of django do you try ?

**Comment by ilizaran** [comment]
django1.7
django_firebird-1.6.4.dist-info

**Comment by mariuz** [comment]
you need to try version from git for django 1.7 (alpha state)

or for stable driver version from pip you will need django 1.6.x

**Comment by mariuz** [comment]
For alpha version of the driver 
pip install Django==1.7.10
git clone git://github.com/maxirobaina/django-firebird.git
cd django-firebird
sudo python setup.py install

for stable driver pip install Django==1.6.11
pip install django-firebird

@maxirobaina you can close this

**Comment by ilizaran** [comment]
Thanks you!
