### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by joffilyfe** [maxirobaina/django-firebird#72]
# Django 1.11 support

Hello folks today early I did see this project and tried to use it with latest django version but I got some errors but with Django 1.8.9 it work like a charm.

I started to see how django core backend has changed before 1.8 but I am not specialized in this core functionalities (django sql core and firebird).

There is some interest in support Django >= 1.10?

Thank you.

**Comment by maxirobaina** [comment]
Hi @joffilyfe 

We are a little delayed supporting new django versions. The [``master``](https://github.com/maxirobaina/django-firebird/tree/master) branch has the last development version with django 1.9.x support. You can check it out and help us testing this version.
The idea is to have support to django 1.11 before this end of year withou jump from 1.9 to 1.11 directly.

Also, We have a mailing list at https://groups.google.com/forum/#!forum/django-firebird-dev
Please join us for this kind of discussion.
Regards

**Comment by joffilyfe** [comment]
This is awesome @maxirobaina, thank you.

I will read about this migration to try help your team.

thank you.
