### ISSUE TITLE
How can I test and use in production with embedded firebird?

### ISSUE THREAD

**Issue by ikresoft** [maxirobaina/django-firebird#74]
I would like to use it as embedded database is it possible? and bcs of gunicorn workers I am asking if somebody try it. What are performance with this kind of approach.

**Comment by maxirobaina** [comment]
Hi @ikresoft 
No, I never test it with embedded database and I don't think this is a good idea.
Anyway you can try to ask this at http://groups.google.com/group/django-firebird-dev  maybe other users tried this.

Regards
