### ISSUE TITLE
manage.py migrate wron

### ISSUE THREAD

**Issue by gustavodiego01** [maxirobaina/django-firebird#75]
Hi, 
I have an error doing manage.py migrate

pip freeze
Django==1.8.1
django-firebird==1.8
fdb==1.7
python = 2.7.10
Firebird = 2.6
Windows 7

![error firebird](https://cloud.githubusercontent.com/assets/7283314/26517787/eaeb4d16-426d-11e7-968c-3e00b752f638.png)

please helpme, Firebird es good and I plan to keep using it

Gustavo Diego

**Comment by maxirobaina** [comment]
Hi @gustavodiego01
Please don't paste an image, it looks truncated.
Copy and paste the entire output traceback.

And remember the best place to request support is at http://groups.google.com/group/django-firebird-dev

Regards.
