### ISSUE TITLE
inspectdb support

### ISSUE THREAD

**Issue by lsnk** [maxirobaina/django-firebird#76]
I'm getting empty classes using inspectdb with django 1.8.
As I can understand, this feature is not supported. Any chance it will be added in future?

**Comment by maxirobaina** [comment]
Hi @lsnk 
inspectdb is supported. Please, provide us more information about your environment, OS, Firebird version, python and django-firebird version, etc.

**Comment by lsnk** [comment]
Win10, Yaffil server (FDB library works fine with it). Charset is WIN1251. Python 3.5.2.
The inspectdb script fills only tablenames.
I need this database as a secondary one, so my test config is:

`DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'fb': {
        'ENGINE': 'firebird',
        ....
        'HOST': '127.0.0.1',        # Your host machine
        'PORT': '3050',             # If is empty, use default 3050
        'OPTIONS': {
            'charset': 'WIN1251',
        }
    }
}`

I'm getting all tables like this:
`class DISTR(models.Model):

    class Meta:
        managed = False
        db_table = 'd i s t r '`

Any more actions I should do before running inspectdb?

**Comment by maxirobaina** [comment]
Ah, ok the **default** connection is not on firebird engine.

Do you run inspectdb like this ?

`python manage.py inspectdb --database=fb > your_app/models.py`

If this dosen't works try setting the firebird connection as **default** connection an run it again (without --database flag)

**Comment by lsnk** [comment]
Im doing --database=fb exactly and it gives empty models.
Same thing with 'default' firebird database.

**Comment by maxirobaina** [comment]
Are you using django 1.8 and django-firebird 1.8 ?

Unfortunately I don't have Yaffil server and Win 10 to test.

**Comment by lsnk** [comment]
Yeah, django 1.8.18 and django-firebird 1.8.2

**Comment by lsnk** [comment]
Any chance I can debug this myself. Or I can supply you with *.fbk backup.

**Comment by maxirobaina** [comment]
> Any chance I can debug this myself

Of course!!, you can clone or fork this project and test it by youself, there are  isolated tests to try.
You can send me a .fbk to maxirobaina at gmail dot com.

**Comment by maxirobaina** [comment]
Hi @lsnk 

I do a restore from your fbk. I haven't Yaffil, so I restore using Firebird 2.5 SuperClassic on Ubuntu.
After restore, setting up a new connection alias into a django project, I get the next output (it just a snippet not the full output)

```
$ ./manage.py inspectdb --database unik
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models


class Adres(models.Model):
    kodadres = models.IntegerField()
    nmreg = models.CharField(max_length=50, blank=True, null=True)
    nmnp = models.CharField(max_length=50, blank=True, null=True)
    nmstt = models.CharField(max_length=50, blank=True, null=True)
    nmst = models.CharField(max_length=50, blank=True, null=True)
    dom = models.CharField(max_length=50, blank=True, null=True)
    kvartira = models.CharField(max_length=100, blank=True, null=True)
    liter = models.CharField(max_length=50, blank=True, null=True)
    komn = models.IntegerField(blank=True, null=True)
    prim = models.CharField(max_length=500, blank=True, null=True)
    invn = models.CharField(max_length=13, blank=True, null=True)
    kodf = models.IntegerField()
    usid = models.IntegerField(blank=True, null=True)
    dtiu = models.DateTimeField(blank=True, null=True)
    cus = models.IntegerField(blank=True, null=True)
    cdt = models.DateTimeField(blank=True, null=True)
    prim2 = models.CharField(max_length=2000, blank=True, null=True)
    ukad = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'adres'
        unique_together = (('kodadres', 'kodf'),)
```

**Comment by lsnk** [comment]
That's a correct output, i'm getting empty table though.
So you just started "startproject", added fb database to settings and ran inspectdb right?

**Comment by maxirobaina** [comment]
> So you just started "startproject", added fb database to settings and ran inspectdb right?

Yes, django-admin startproject unik, edit setting, add a new connection alias and run inspectdb.
Also, I test over an existent project and this works ok.

I suspect could be a problem with Yaffil.

On a existent Yaffil DB try to run this sql statement

```
select
      lower(trim(rdb$relation_name)),
      case when RDB$VIEW_BLR IS NULL then 't' else 'v' end as rel_type
from rdb$relations
where rdb$system_flag=0
order by 1 
```

And tell me what do you get.

**Comment by lsnk** [comment]
I'm getting following output in IBExpert.
http://i.imgur.com/0ZT9Dud.png

**Comment by maxirobaina** [comment]
Aha, seem like is a Yaffil compatibility problem.
Which version of your Yaffil server match with Firebird ?


The output in Firebird 2.5 Server look like this:

LOWER | REL_TYPE
------------ | -------------
adres	|	t
ddocuments	|	t
depts	|	t
distr	|	t
docsowpos	|	t
docsowrig	|	t
documents	|	t
ogrob	|	t
pravo	|	t
registraziya	|	t
rown	|	t
sobstvenniki	|	t
streets	|	t
strtypes	|	t
towns	|	t
twntyp	|	t
workers	|	t

**Comment by lsnk** [comment]
I've got Yaffil 1.3.0.884. So the problem is in compitability between Yaffil and FDB library right?

**Comment by mariuz** [comment]
Best way is to switch to Firebird 2.5 or 3.0 that are well supported by fdb and django firebird driver
