### ISSUE TITLE
Error while preparing SQL statement: Expression evaluation not supported

### ISSUE THREAD

**Issue by ilizaran** [maxirobaina/django-firebird#78]
I get a error with this code, when I remove '/100' there aren't any problem.

        total=DetalleVenta.objects.filter(venta=self).aggregate(
            total=Sum(F('cantidad')*(F('pvp')-F('pvp')*F('descuento')/100)
            ,output_field=models.FloatField())
            )['total']

The system return:
Error while preparing SQL statement:\n- SQLCODE: -902\n- Dynamic SQL Error\n- expression evaluation not supported\n- Strings cannot be divided in dialect 3

Local vars:

Variable | Value
operation | 'SELECT  SUM(("DETALLEVENTAS"."CANTIDAD" * ("DETALLEVENTAS"."PVP" - (("DETALLEVENTAS"."PVP" * "DETALLEVENTAS"."DESCUENTO") / ?)))) AS "TOTAL" FROM "DETALLEVENTAS" WHERE "DETALLEVENTAS"."IDVENTA" = ?'
parameters | (100, 401783)

**Comment by maxirobaina** [comment]
Hi @ilizaran,
Can you test this cloning from master branch (using django 1.10.x)?

Regards.

**Comment by maxirobaina** [comment]
Ok, a kind of workaround without any change in the backend

```
 total=DetalleVenta.objects.filter(venta=self).aggregate(
        total=Sum(F('cantidad')*(F('pvp')-F('pvp')*F('descuento') / Cast(Value(100), output_field=models.IntegerField()))
        ,output_field=models.FloatField())
        )['total']

```

I appreciated if you can test this.

Regards.

**Comment by ilizaran** [comment]
I tested. 
It works very well.
Thanks.
Regards.
