### ISSUE TITLE
New logo for Firebird

### ISSUE THREAD

**Issue by reallinfo** [maxirobaina/django-firebird#94]
Hello, I wanted to contribute to firebird. I designed a logo for it. If you like it, I'll send you files and pr.

![firebird](https://user-images.githubusercontent.com/36298335/39143943-f8b2b84c-4737-11e8-8256-f2cf17b13554.jpg)

**Comment by reallinfo** [comment]
Oh, sorry. I did not know that :)

**Comment by mariuz** [comment]
@reallinfo you can close this , not django-firebird related
