### ISSUE TITLE
[django-firebird 1.11] NameError: global name '_is_relevant_relation' is not defined

### ISSUE THREAD

**Issue by maxirobaina** [maxirobaina/django-firebird#99]
Running migrations raise a NameError: global name '_is_relevant_relation' is not defined

**Comment by LucioZanette** [comment]
For running the _manage.py inspectdb_, I _edited myenv/lib/python3.4/site-packages/firebird/schema.py_ and commented the lines **406**, **407**, **408** e **409**.
Waiting for resolution the bug.

**Comment by maxirobaina** [comment]
Hi @LucioZanette 
It was fixed for 1.11 version.
You can test upgrading your environment using `pip install django-firebird==1.11b1 `
or cloning from stable/1.11.x

Regards

**Comment by LucioZanette** [comment]
Thank you, @maxirobaina 
I'll update and test it.
